#!/usr/bin/env ruby

# gbl = git branch list
#
# Interactive selector for switching git branches.

require 'bundler/inline'

begin
  gemfile do
    source 'https://rubygems.org'
    gem 'tty-prompt', '~> 0.23.1', require: false
  end
rescue => e
  puts "failed to install gems: #{e}"
  raise e
end

require "tty-prompt"
branches = `git branch`
branches = branches.split("\n").map(&:strip).delete_if { |b| b.start_with?("* ") }
prompt = TTY::Prompt.new(interrupt: :exit)
branch = prompt.select("Select branch to switch to:", branches)
`git checkout #{branch}`
