#!/usr/bin/env ruby

# Downloads a YouTube video as an MP3.
#
# Requires `youtube-dl` to be installed
#
# USAGE:
#
#   ytmp3 https://youtube.com/video?id=whatever
#
system("youtube-dl -x --audio-format mp3 --audio-quality 0 #{ARGV.join(" ")}")
